name = "reader-auth-api"
compatibility_date = "2024-01-01"

# KV 命名空间绑定 (已创建: LICENSE_KV, ID: c909ee536beb4d13aded0242c78e27a2)
[[kv_namespaces]]
binding = "LICENSE_KV"
id = "c909ee536beb4d13aded0242c78e27a2"
preview_id = "c909ee536beb4d13aded0242c78e27a2"
